"""Initial migration.

Revision ID: 57bec17e94c8
Revises: 
Create Date: 2020-08-17 21:44:05.316381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bec17e94c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changeLog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_details', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('is_resolved', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userModel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=16), nullable=True),
    sa.Column('userDescription', sa.String(length=128), nullable=True),
    sa.Column('userID', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userModel')
    op.drop_table('feedback')
    op.drop_table('changeLog')
    # ### end Alembic commands ###
