"""empty message

Revision ID: c34f459b0c98
Revises: dfec0c012644
Create Date: 2020-03-14 23:29:14.647607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c34f459b0c98"
down_revision = "dfec0c012644"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contact_details", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    # ### end Alembic commands ###
