"""empty message

Revision ID: e3933bd46efe
Revises: acaf607b96dc
Create Date: 2020-03-12 16:14:27.700390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3933bd46efe'
down_revision = 'acaf607b96dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userModel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=16), nullable=True),
    sa.Column('userDescription', sa.String(length=128), nullable=True),
    sa.Column('userID', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    op.drop_index('email', table_name='zhihu_user')
    op.drop_index('username', table_name='zhihu_user')
    op.drop_table('zhihu_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zhihu_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('_password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_activate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('permission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'zhihu_user', ['username'], unique=True)
    op.create_index('email', 'zhihu_user', ['email'], unique=True)
    op.drop_table('userModel')
    # ### end Alembic commands ###
